#ifndef INCLUDE_SIMPLE3D_GRAPHICS_MODELS_SPHERE_H_
#define INCLUDE_SIMPLE3D_GRAPHICS_MODELS_SPHERE_H_

namespace Simple3D {

}  // namespace Simple3D

#endif  // INCLUDE_SIMPLE3D_GRAPHICS_MODELS_SPHERE_H_
