set(SIMPLE3D_GITHUB_PREFIX "https://github.com" CACHE STRING "")
set(SIMPLE3D_GITHUB_REPO_PATH "ItIsApachee/simple3d" CACHE STRING "")
set(SIMPLE3D_GITHUB_DOWNLOAD_RELEASE_TAG "prerelease" CACHE STRING "")
set(SIMPLE3D_GITHUB_WEB_CLIENT_ASSET_NAME "web-client.tar.gz" CACHE STRING "")

# Path to download is ${SIMPLE3D_GITHUB_PREFIX}/${SIMPLE3D_GITHUB_REPO_PATH}/releases/download/${SIMPLE3D_GITHUB_DOWNLOAD_RELEASE_TAG}/${SIMPLE3D_GITHUB_WEB_CLIENT_ASSET_NAME}
