name: Build project and create release with resulting artifacts

on:
  schedule:
    - cron:  '0 0,12 * * *'

  workflow_dispatch:

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout emsdk
        uses: actions/checkout@v4
        with:
          repository: emscripten-core/emsdk
          path: emsdk

      - name: Install Emscripten
        working-directory: ./emsdk
        run: |
          # Install Emscripten via emsdk

          set -x
          
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh

          # Verify installation
          em++ -v

          echo "S3D_EMSCRIPTEN_CMAKE_TOOLCHAIN=$(dirname -- $(which emcc))/cmake/Modules/Platform/Emscripten.cmake" >> $GITHUB_ENV
          
          echo 'source "$GITHUB_WORKSPACE/emsdk/emsdk_env.sh"' >> $HOME/.bash_profile

      - name: Build
        run: |
          cmake -S . -B build -DSIMPLE3D_EMSCRIPTEN_CMAKE_TOOLCHAIN_FILE=$S3D_EMSCRIPTEN_CMAKE_TOOLCHAIN -DCMAKE_BUILD_TYPE:STRING=Release
          cmake --build build

          # Verify web client was built
          file build/simple3d/web/client/out/index.html
          file build/simple3d/web/client/out/index.js
          file build/simple3d/web/client/out/index.wasm
