name: Build project and create release with resulting artifacts

on:
  schedule:
    - cron:  '0 0,12 * * *'

  workflow_dispatch:

jobs:
  build-and-release:
    name: Build project and create release with resulting artifacts
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: simple3d

      - name: Checkout emsdk
        uses: actions/checkout@v4
        with:
          repository: emscripten-core/emsdk
          path: emsdk

      - name: Install Emscripten
        working-directory: ./emsdk
        run: |
          # Install Emscripten via emsdk

          set -x

          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh

          # Verify installation
          em++ -v

          echo "S3D_EMSCRIPTEN_CMAKE_TOOLCHAIN=$(dirname -- $(which emcc))/cmake/Modules/Platform/Emscripten.cmake" >> $GITHUB_ENV

      - name: Build
        working-directory: ./simple3d
        run: |
          # Actual build step

          set -x

          # Make build artifacts dir

          mkdir -p $GITHUB_WORKSPACE/out

          cmake -S . -B build -DSIMPLE3D_EMSCRIPTEN_CMAKE_TOOLCHAIN_FILE=$S3D_EMSCRIPTEN_CMAKE_TOOLCHAIN -DCMAKE_BUILD_TYPE:STRING=Release
          cmake --build build

          # Package client
          tar -czvf $GITHUB_WORKSPACE/out/web-client.tar.gz -C ./build/simple3d/web/client/out .

      - name: Release
        uses: softprops/action-gh-release@v2
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          files: ./out/**
          prerelease: true
          name: "[CI] Automatic pre-release (Commit: ${{ github.sha }})"
          tag_name: prerelease
          body: ""  # Generate release notes?
